/**
 * 00_Config.gs - DIGIASHA FIELD MONITORING SYSTEM
 * File Konfigurasi Spreadsheet & Folder Google Drive
 */
const CONFIG = {
  MAIN_SPREADSHEET_ID: "1JbCMIePpNfPRfev7UIjyO763BfmJqzgtrLDMA0oFqVI",
  HR_SOURCE_ID: "1h2NiNffCNUrtoauLkdJXBKXTyOOnxBh6vPvLowOo5M8",
  DEALER_FACILITY_SOURCE_ID: "1ST9KvTCE9iyhz0GD4gRQIBt6gS_3pnGOUZbHYkAO75M",

  SHEETS: {
    EMPLOYEE: "M_EMPLOYEE",
    DEALER: "M_DEALER",
    FACILITY_UNIT: "M_FACILITY_UNIT",
    GPS_DEVICE: "M_GPS_DEVICE",
    ASSIGNMENT: "T_ASSIGNMENT",
    VISIT_HEADER: "TR_LAPORAN_VISIT",
    VISIT_UNIT: "TR_VISIT_UNIT_CHECK",
    GPS_MAINTENANCE: "TR_GPS_MAINTENANCE",
    ONBOARDING: "TR_ONBOARDING_LOG",
    FAC_AUDIT: "TR_GPS_FAC_CHECK",
    PRIORITY_LOG: "LOG_PRIORITY_DAILY",
    ABSENSI: "TR_ABSENSI_LOG",
    AUDIT_TRAIL: "SYS_AUDIT_TRAIL"
  },

  DRIVE_FOLDERS: {
    ONBOARDING_ID: "1Damd9YO6LqJyxbTZMxz_UZDWWuOU7AvJ",
    VISIT_FOTO_ID: "18VPAgr14_kkf3Y3nBBp9d-e4Vcn-fcDK"
  }
};
